// <auto-generated />
using Backend.Infrastructure.Pipeline;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Infrastructure.Pipeline.Migrations
{
    [DbContext(typeof(PipelineDbContext))]
    partial class PipelineDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Backend.Core.Library.MasterMedia", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("account_id");

                    b.Property<string>("BestQuality")
                        .HasColumnType("TEXT")
                        .HasColumnName("best_quality");

                    b.Property<string>("MediaKind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("media_kind");

                    b.Property<string>("NormalizedKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("normalized_key");

                    b.Property<string>("PosterUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("poster_url");

                    b.Property<double?>("Rating")
                        .HasColumnType("REAL")
                        .HasColumnName("rating");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at");

                    b.Property<int>("VariantCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("variant_count");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "MediaKind", "Title");

                    b.ToTable("master_media", (string)null);
                });

            modelBuilder.Entity("Backend.Core.Library.MediaVariant", b =>
                {
                    b.Property<string>("AccountId")
                        .HasColumnType("TEXT")
                        .HasColumnName("account_id");

                    b.Property<string>("MediaKind")
                        .HasColumnType("TEXT")
                        .HasColumnName("media_kind");

                    b.Property<string>("StreamId")
                        .HasColumnType("TEXT")
                        .HasColumnName("stream_id");

                    b.Property<string>("AudioLanguages")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("audio_languages");

                    b.Property<string>("AudioTag")
                        .HasColumnType("TEXT")
                        .HasColumnName("audio_tag");

                    b.Property<string>("CategoryId")
                        .HasColumnType("TEXT")
                        .HasColumnName("category_id");

                    b.Property<string>("ContainerExtension")
                        .HasColumnType("TEXT")
                        .HasColumnName("container_extension");

                    b.Property<bool>("IsHdr")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_hdr");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("label");

                    b.Property<string>("MasterId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("master_id");

                    b.Property<string>("PosterUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("poster_url");

                    b.Property<string>("Quality")
                        .HasColumnType("TEXT")
                        .HasColumnName("quality");

                    b.Property<int>("QualityScore")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quality_score");

                    b.Property<double?>("Rating")
                        .HasColumnType("REAL")
                        .HasColumnName("rating");

                    b.Property<string>("RawTitle")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("raw_title");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.HasKey("AccountId", "MediaKind", "StreamId");

                    b.HasIndex("MasterId");

                    b.HasIndex("AccountId", "MediaKind", "CategoryId");

                    b.ToTable("media_variants", (string)null);
                });

            modelBuilder.Entity("Backend.Core.Library.NormalizationJob", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("account_id");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER")
                        .HasColumnName("attempts");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT")
                        .HasColumnName("error");

                    b.Property<long?>("FinishedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("finished_at");

                    b.Property<int>("ItemCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_count");

                    b.Property<string>("LockedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("locked_by");

                    b.Property<string>("MediaKind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("media_kind");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("payload");

                    b.Property<long?>("StartedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Status", "Id");

                    b.HasIndex("AccountId", "MediaKind", "Status");

                    b.ToTable("normalization_jobs", (string)null);
                });

            modelBuilder.Entity("Backend.Core.Library.MediaVariant", b =>
                {
                    b.HasOne("Backend.Core.Library.MasterMedia", "Master")
                        .WithMany("Variants")
                        .HasForeignKey("MasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Master");
                });

            modelBuilder.Entity("Backend.Core.Library.MasterMedia", b =>
                {
                    b.Navigation("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
